CARGO ?= cargo
CC ?= cc
GDB ?= gdb

CARGO_TARGET_DIR ?= target
PROFILE ?= debug

LIBCORUS_A := $(CARGO_TARGET_DIR)/$(PROFILE)/libcorus.a
C_ABI_DIR := target/c-abi
C_ABI_SRC := ctests/writecore_smoke.c
C_ABI_EXE := $(C_ABI_DIR)/writecore_smoke
C_ABI_CORE := $(C_ABI_DIR)/writecore_smoke.core
C_ABI_GDB := $(C_ABI_DIR)/gdb.txt
ORIGINAL_C_UNIT_DIR := target/original-c-unit
ORIGINAL_C_UNIT_EXE := $(ORIGINAL_C_UNIT_DIR)/coredumper_unittest_rust
ORIGINAL_C_UNIT_LOG := $(ORIGINAL_C_UNIT_DIR)/output.txt

.PHONY: build tests test-rust test-c-abi test-original-c-unit clean-c-abi clean-original-c-unit

build:
	$(CARGO) build -p corus

tests:
	$(MAKE) test-rust
	$(MAKE) test-c-abi
	$(MAKE) test-original-c-unit

# Run the Rust tests under nextest with output uncaptured, so per-test
# diagnostics (e.g. the strategy timing fractions) appear in CI logs. nextest
# does not run doctests, so run those separately with plain `cargo test --doc`.
# Override the runner with `NEXTEST=0` to fall back to `cargo test`.
NEXTEST ?= 1
test-rust:
ifeq ($(NEXTEST),1)
	$(CARGO) nextest run --workspace --no-capture
	$(CARGO) test --workspace --doc
else
	$(CARGO) test --workspace
endif

$(LIBCORUS_A):
	$(CARGO) build -p corus

$(C_ABI_EXE): $(C_ABI_SRC) $(LIBCORUS_A)
	mkdir -p $(C_ABI_DIR)
	$(CC) -g -O0 -Icoredumper $(C_ABI_SRC) $(LIBCORUS_A) -lpthread -ldl -lm -o $@

test-c-abi: $(C_ABI_EXE)
	rm -f $(C_ABI_CORE) $(C_ABI_GDB)
	$(C_ABI_EXE) $(C_ABI_CORE)
	test -s $(C_ABI_CORE)
	$(GDB) -q -batch -ex bt $(C_ABI_EXE) $(C_ABI_CORE) > $(C_ABI_GDB)
	grep -q "Core was generated by" $(C_ABI_GDB)
	grep -q "main" $(C_ABI_GDB)

$(ORIGINAL_C_UNIT_EXE): coredumper/coredumper_unittest.c $(LIBCORUS_A)
	mkdir -p $(ORIGINAL_C_UNIT_DIR)
	$(CC) -g -O0 -Icoredumper coredumper/coredumper_unittest.c $(LIBCORUS_A) -lpthread -ldl -lm -o $@

test-original-c-unit: $(ORIGINAL_C_UNIT_EXE)
	rm -f $(ORIGINAL_C_UNIT_LOG)
	cd $(ORIGINAL_C_UNIT_DIR) && \
		if command -v timeout >/dev/null 2>&1; then \
			timeout 240s ./coredumper_unittest_rust > output.txt 2>&1; \
		else \
			./coredumper_unittest_rust > output.txt 2>&1; \
		fi
	grep -q "PASS" $(ORIGINAL_C_UNIT_LOG)

clean-c-abi:
	rm -rf $(C_ABI_DIR)

clean-original-c-unit:
	rm -rf $(ORIGINAL_C_UNIT_DIR)