//! An uncompressed core produced by `write_core_dump_to_fd` **loads in gdb** and
//! `bt` shows the correct frames.
//!
//! Runs the `dump_self` example (which dumps itself from a known call stack
//! `deep_frame_a -> b -> c`), then loads the core in gdb and asserts the backtrace
//! and thread list are sane. Skips cleanly if gdb is unavailable / ptrace is
//! denied.

mod common;

use std::process::Command;

use common::have_tool;

fn example_path() -> Option<std::path::PathBuf> {
    // The integration test binary lives in target/<...>/deps; the example is a
    // sibling under examples/. Locate it relative to the current exe.
    let mut dir = std::env::current_exe().ok()?;
    dir.pop(); // deps
    dir.pop(); // debug (or profile dir)
    dir.push("examples");
    dir.push("dump_self");
    if dir.exists() { Some(dir) } else { None }
}

#[test]
fn core_loads_in_gdb_with_correct_backtrace() {
    if !have_tool("gdb") {
        eprintln!("skipping: gdb not available");
        return;
    }
    let exe = match example_path() {
        Some(p) => p,
        None => {
            eprintln!(
                "skipping: dump_self example not built (run `cargo build --example dump_self`)"
            );
            return;
        }
    };

    let core = std::env::temp_dir().join(format!("cd_gdbload_{}.core", std::process::id()));
    let _ = std::fs::remove_file(&core);

    // Produce the core.
    let out = Command::new(&exe)
        .arg(&core)
        .output()
        .expect("run dump_self");
    if !out.status.success() {
        // exit 2 from the example means the dump itself failed (e.g. no ptrace).
        eprintln!(
            "skipping: dump_self failed (status {:?}); likely no ptrace permission",
            out.status.code()
        );
        return;
    }
    assert!(core.exists(), "core file should exist");
    let meta = std::fs::metadata(&core).unwrap();
    assert!(meta.len() > 0, "core file should be non-empty");

    // Load in gdb and capture threads + backtrace.
    let gdb = Command::new("gdb")
        .args(["-q", "-batch", "-ex", "info threads", "-ex", "bt"])
        .arg(&exe)
        .arg(&core)
        .output()
        .expect("run gdb");
    let text = String::from_utf8_lossy(&gdb.stdout);
    let _ = std::fs::remove_file(&core);

    // gdb must recognize the core and reconstruct our call chain.
    assert!(
        text.contains("Core was generated by"),
        "gdb did not accept the core:\n{text}"
    );
    // The distinctive call stack from dump_self.
    for frame in ["deep_frame_c", "deep_frame_b", "deep_frame_a"] {
        assert!(
            text.contains(frame),
            "backtrace missing frame `{frame}`:\n{text}"
        );
    }
    // Multiple threads (main + 2 workers) should appear.
    let thread_lines = text.matches("Thread 0x").count();
    assert!(
        thread_lines >= 3,
        "expected >=3 threads in core, got {thread_lines}:\n{text}"
    );
}
