//! Rust API integration tests for loadable cores, size limits, and compression.

mod common;

use std::{fs::write, path::Path, process::Command};
use tempfile::{Builder, NamedTempFile};

use common::ptrace_denied;

/// Create a named temporary output path with the requested suffix.
fn temp_output(prefix: &str, suffix: &str) -> NamedTempFile {
    Builder::new()
        .prefix(prefix)
        .suffix(suffix)
        .tempfile()
        .expect("create temp output")
}

fn gdb_backtrace(exe: &Path, core: &Path) -> Option<String> {
    let out = Command::new("gdb")
        .args(["-q", "-batch", "-ex", "thread apply all bt"])
        .arg(exe)
        .arg(core)
        .output();
    out.ok()
        .map(|o| String::from_utf8_lossy(&o.stdout).into_owned())
}

#[test]
fn rust_api_writes_loadable_core() -> Result<(), Box<dyn std::error::Error>> {
    let core = temp_output("cd_rustapi_", ".core");

    // SAFETY: this test process obeys the suspend contract.
    let r = unsafe { corus::CoreDump::builder().write_to_path(core.path()) };
    if ptrace_denied(r, "Rust API dump") {
        return Ok(());
    }
    assert!(core.path().metadata().map(|m| m.len() > 0).unwrap_or(false));

    if which::which("gdb").is_ok() {
        let exe = std::env::current_exe()?;
        // gdb against the test binary itself: the core came from this process.
        let bt = gdb_backtrace(&exe, core.path()).expect("run gdb");
        assert!(
            bt.contains("Core was generated by"),
            "gdb should load the Rust-API core:\n{bt}"
        );
        assert!(
            bt.contains("rust_api_writes_loadable_core"),
            "Rust API core should unwind into the caller:\n{bt}"
        );
    }
    Ok(())
}

#[test]
fn rust_api_max_length_truncates() -> Result<(), Box<dyn std::error::Error>> {
    let core = temp_output("cd_rustlimit_", ".core");
    let limit = 64 * 1024;
    let r = unsafe {
        corus::CoreDump::builder()
            .max_length(limit)
            .write_to_path(core.path())
    };
    if ptrace_denied(r, "Rust API limited dump") {
        return Ok(());
    }
    let len = core.path().metadata().unwrap().len() as usize;
    assert!(len <= limit, "limited core {len} should be <= {limit}");
    Ok(())
}

#[test]
fn rust_api_gzip_decompresses_to_loadable_core() -> Result<(), Box<dyn std::error::Error>> {
    if which::which("gzip").is_err() {
        eprintln!("skipping: gzip not available");
        return Ok(());
    }
    let gz = temp_output("cd_gz_", ".core.gz");

    let r = unsafe {
        corus::CoreDump::builder()
            .compression(corus::Compression::Gzip)
            .write_to_path(gz.path())
    };
    if ptrace_denied(r, "Rust API gzip dump") {
        return Ok(());
    }
    let compressed_len = gz.path().metadata().unwrap().len();
    assert!(compressed_len > 0, "compressed core should be non-empty");

    // Decompress and confirm it's a valid ELF core.
    let core = temp_output("cd_gz_", ".core");
    let ok = Command::new("gzip")
        .args(["-d", "-c"])
        .arg(gz.path())
        .output()
        .map(|o| {
            write(core.path(), &o.stdout).ok();
            o.status.success() && o.stdout.starts_with(b"\x7fELF")
        })
        .unwrap_or(false);
    assert!(ok, "gunzip output should start with ELF magic");

    if which::which("gdb").is_ok() {
        let exe = std::env::current_exe()?;
        let bt = gdb_backtrace(&exe, core.path()).expect("run gdb");
        assert!(
            bt.contains("Core was generated by"),
            "decompressed core should load in gdb"
        );
    }
    Ok(())
}

#[test]
fn rust_api_gzip_honors_max_length() -> Result<(), Box<dyn std::error::Error>> {
    if which::which("gzip").is_err() {
        eprintln!("skipping: gzip not available");
        return Ok(());
    }
    let gz = temp_output("cd_gz_limit_", ".core.gz");
    let core = temp_output("cd_gz_limit_", ".core");
    let limit = 64 * 1024;

    let r = unsafe {
        corus::CoreDump::builder()
            .max_length(limit)
            .compression(corus::Compression::Gzip)
            .write_to_path(gz.path())
    };
    if ptrace_denied(r, "Rust API limited gzip dump") {
        return Ok(());
    }

    let out = Command::new("gzip")
        .args(["-d", "-c"])
        .arg(gz.path())
        .output()
        .expect("gunzip");
    assert!(out.status.success(), "gunzip failed");
    write(core.path(), &out.stdout).unwrap();
    assert!(out.stdout.starts_with(b"\x7fELF"));
    assert_eq!(
        out.stdout.len(),
        limit,
        "decompressed limited core should be exactly {limit} bytes"
    );
    Ok(())
}
